apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: esaenz
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: app-deployment
        image: harbor.dev.afsmtddso.com/esaenz-harbor-project/app@sha256:edddeece4b7b7a8c074974ca36e3f564378b007d94864d94a6eaae97a08edd7f
        ports:
        - containerPort: 5000
